# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Engineerious"

# A description of your site for social meta tag, search engines, and feed.xml
description: "BlogInn is a bold theme for the Jekyll blogging platform. Available for purchase at ThemeForest.net."

# Tagline near the site title
tagline: "IT tutorials, thoughts, stories, and ideas."

# The subpath of site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://engineerious.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: "https://arthurmiller.github.io/engineerious/"
- text: About the blog
  url: "https://arthurmiller.github.io/engineerious/about/"
- text: About the contributors
  url: "https://arthurmiller.github.io/engineerious/style-guide/"
- text: Articles
  url: "https://arthurmiller.github.io/engineerious/tags/"

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "About this blog"
author_bio: "The authors of this blog are active software engineers from a diverse technical background looking to help others increase their knowledge within specific subject areas. We are also looking to assist others in understanding potentially complex subject matters, inspiring ideas, and gather feedback from the engineering community."
author_url:  "http://engineerious.com"
author_location: "Arizona"
author_image: /images/authorimage.png

# Author1 information - author info at the bottom of the post
author1_name: "Arthur Miller"
author1_bio: "Arthur is a software engineer that loves to dive into new technologies while at the same time examining where improvements can be made on existing technologies and processes. Whether it is in performance, reliability, resilience, or even the software engineering process itself, there is always something to be improved, and Arthur eagerly seeks out those opportunities. Currently, Arthur is a Software Engineering Team Lead by official title but loves both the hands-on side of software engineering (where he can write code and create value) as well as the software engineering management side (where he can improve processes, lead innovative change, and assist in building the skills and careers of others)."
author1_url: ""
author1_location: "Arizona"
author1_image: /images/authorimage.png

# Author2 information - author info at the bottom of the post
author2_name: "Someone"
author2_bio: ""
author2_url:  ""
author2_location: "Arizona"
author2_image: /images/authorimage.png

# Author3 information - author info at the bottom of the post
author3_name: "Someone Else"
author3_bio: ""
author3_url:  ""
author3_location: "Arizona"
author3_image: /images/authorimage.png

# Sidebar Add banner
banner_url: "http://justgoodthemes.com"
banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username: "username"
facebook_username: "username"
googleplus_username: "+username"
github_username: "username"
codepen_username: "username"
dribbble_uername: "username"
medium_username: "@username"
instagram_username: "username"
pinterest_username: "username"
linkedin_username: "username"
weibo_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
